version: "3.8"
services:
  nacos1:
    restart: always
    image: nacos/nacos-server:2.0.3
    container_name: nacos
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      NACOS_AUTH_ENABLE: "true"
      NACOS_AUTH_TOKEN_EXPIRE_SECONDS: 18000
      JVM_XMS: 128m
      JVM_XMX: 128m
      JVM_MS: 64m
      JVM_MMS: 64m
      NACOS_REPLICAS: 1
      MYSQL_DATABASE_NUM: 1
      PREFER_HOST_MODE: ip
      MYSQL_SERVICE_DB_NAME: nacos
      # 以下内容，请根据具体情况修改
      # nacos的模式(单体或集群)
      MODE: standalone
      # nacos数据库类型
      SPRING_DATASOURCE_PLATFORM: mysql
      # nacos数据库地址
      MYSQL_SERVICE_HOST: 172.16.0.11
      # nacos数据库端口
      MYSQL_SERVICE_PORT: 3306
      # nacos数据库账号
      MYSQL_SERVICE_USER: root
      # nacos数据库密码
      MYSQL_SERVICE_PASSWORD: zhang147852
    volumes:
      - /app/nacos/logs:/home/nacos/logs
